{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute'
         html_class='full'}
         <select class="{eq($html_class,'half')|choose('box','halfbox')}" name="{$attribute_base}_ezstring_data_text_{$attribute.id}">
         {section loop=ezini('Settings', 'avialableRepositories','svn.ini')}
         <option value="{$:item}" {section show=$attribute.data_text|wash(xhtml)|eq($:item)} selected{/section}>{$:item}</option>
         {/section}
         </select>
{/default}