{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default class_content=$attribute.class_content
     class_list=fetch( class, list, cond( $class_content.class_constraint_list|gt(0),hash( class_filter,$class_content.class_constraint_list ),hash() ) )
     can_create=true()
     new_object_initial_node_placement=false()
     related_items=array()
     browse_object_start_node=$class_content.default_selection.node_id
     browse_object_browse_type=$class_content.selection_type
     allow_edit=$class_content.allow_edit}

{include uri="design:content/datatype/edit/ezobjectrelationbrowse_controls.tpl"}

{switch match=$class_content.selection_type}
	{* listbox *}
	{case match=2}
	<p>
	{section loop=$attribute.content.relation_browse}
		{set related_items=$related_items|append($:item.contentobject_id)}
	{/section}
		<input type="hidden" name="SelectionType" value="2" />
		<input type="hidden" name="{$attribute_base}_id[]" value="{$attribute.id}" />
		
		<select name="SelectedObjectIDArray_{$attribute.id}[]" multiple size="10">
			{section show=$attribute.contentclass_attribute.is_required|not}
				 <option value="0" {section show=or(eq($related_items|count,0),eq($attribute.content.relation_browse|count,0))}selected="selected"{/section}>{'No relation'|i18n( 'design/standard/content/datatype' )}</option>
			{/section}
	
			{let parent_node=fetch( content, node, hash( node_id, $browse_object_start_node ) )}
				{section var=node loop=fetch( content, list,
						      hash( parent_node_id, $parent_node.node_id,
							    sort_by, $parent_node.sort_array ) )}
					<option value="{$node.contentobject_id}" {$related_items|contains($node.contentobject_id)|choose( '', 'selected="selected"' )}>{$node.name|wash}</option>
				{/section}
			{/let}
		</select>
	</p>
	{/case}
	
	
	{* dropdown *}
	{case match=3}
	<p>
	{section loop=$attribute.content.relation_browse}
		{set related_items=$related_items|append($:item.contentobject_id)}
	{/section}
		<input type="hidden" name="SelectionType" value="3" />
		<input type="hidden" name="{$attribute_base}_id[]" value="{$attribute.id}" />

		<select name="SelectedObjectIDArray_{$attribute.id}[]">
			{section show=$attribute.contentclass_attribute.is_required|not}
				 <option value="0" {section show=or(eq($related_items|count,0),eq($attribute.content.relation_browse|count,0))}selected="selected"{/section}>{'No relation'|i18n( 'design/standard/content/datatype' )}</option>
			{/section}

			{let parent_node=fetch( content, node, hash( node_id, $browse_object_start_node ) )}
				{section var=node loop=fetch( content, list,
						      hash( parent_node_id, $parent_node.node_id,
							    sort_by, $parent_node.sort_array ) )}
					<option value="{$node.contentobject_id}" {$related_items|contains($node.contentobject_id)|choose( '', 'selected="selected"' )}>{$node.name|wash}</option>
				{/section}
			{/let}
		</select>
	</p>
	{/case}
	
	
	{* checkbox *}
	{case match=4}
	<p>
	{section loop=$attribute.content.relation_browse}
		{set related_items=$related_items|append($:item.contentobject_id)}
	{/section}
		<input type="hidden" name="SelectionType" value="4" />
		<input type="hidden" name="{$attribute_base}_id[]" value="{$attribute.id}" />
		{let parent_node=fetch( content, node, hash( node_id, $browse_object_start_node ) )}
			{section var=node loop=fetch( content, list,
					      hash( parent_node_id, $parent_node.node_id,
						    sort_by, $parent_node.sort_array ) )}
				<input type="checkbox" name="SelectedObjectIDArray_{$attribute.id}[]" value="{$node.contentobject_id}" {$related_items|contains($node.contentobject_id)|choose( '', 'checked="checked"' )}>{$node.name|wash}<br/>
			{/section}
		{/let}
	</p>
	{/case}
	
	{* browse *}
	{case}
	{section show=$attribute.content.relation_browse}
		<table class="list" width="80%" cellspacing="0" cellpadding="0" border="0">
		<tr>
		    <th>
		    </th>
			    {section show=eq($allow_edit,1)}
				    <th>
				    </th>
			    {/section}
		    <th>
			Order
		    </th>
		    <th>
		    </th>
		</tr>
		{section name=Relation loop=$attribute.content.relation_browse sequence=array(bglight,bgdark)}
			<tr class="{$:sequence}">
				<td width="1" align="right">
					<input type="checkbox" name="{$attribute_base}_selection[{$attribute.id}][]" value="{$:item.contentobject_id}" />
				</td>
				{section show=eq($allow_edit,1)}
				<td width="1">
					{section show=$:item.is_modified|not}
						<input class="button" type="image" name="CustomActionButton[{$attribute.id}_edit_objects_{$:item.contentobject_id}]" value="{'Edit'|i18n('design/standard/content/datatype')}" src={"edit.png"|ezimage} />
					{/section}
				</td>
				{/section}
				<td width="1">
					<input size="2" type="text" name="{$attribute_base}_priority[{$attribute.id}][]" value="{$:item.priority}" />
				</td>
				<td>
				{section show=$:item.is_modified}
				    {let object=fetch(content,object,hash(object_id,$:item.contentobject_id,
									  object_version,$:item.contentobject_version))
					 version=fetch(content,version,hash(object_id,$:item.contentobject_id,
									    version_id,$:item.contentobject_version))}
					<table cellspacing="0" cellpadding="0" border="0">
					{section name=Attribute loop=$:version.contentobject_attributes} 
					<tr>
						<td>
							{$:item.contentclass_attribute.name}
						</td>
						<td>
							{attribute_edit_gui attribute_base=concat($attribute_base,'_ezorl_edit_object_',$Relation:item.contentobject_id)
								html_class='half'
								attribute=$:item}
						</td>
					</tr>
					{/section}
					</table>
				    {/let}
				{section-else}
				    {content_view_gui view=embed content_object=fetch(content,object,hash(object_id,$:item.contentobject_id,
													  object_version,$:item.contentobject_version))}
				{/section}
				</td>
			</tr>
		{/section}
		</table>
	{section-else}
		<p>{'There are no related objects.'|i18n( 'design/standard/content/datatype' )}</p>
	{/section}
	{/case}
{/switch}




<div class="buttonblock">

{section show=lt($class_content.selection_type,2)}
	{section show=$attribute.content.relation_browse}
	    <input class="button" type="submit" name="CustomActionButton[{$attribute.id}_remove_objects]" value="{'Remove selected'|i18n('design/standard/content/datatype')}" />
	    {section show=eq($allow_edit,1)}
		<input class="button" type="submit" name="CustomActionButton[{$attribute.id}_edit_objects]" value="{'Edit selected'|i18n('design/standard/content/datatype')}" />
	    {section-else}
		 <input class="button-disabled" type="submit" name="CustomActionButton[{$attribute.id}_edit_objects]" value="{'Edit selected'|i18n('design/standard/content/datatype')}" disabled="disabled" />
	    {/section}
	{section-else}
		<input class="button-disabled" type="submit" name="CustomActionButton[{$attribute.id}_remove_objects]" value="{'Remove selected'|i18n( 'design/standard/content/datatype' )}" disabled="disabled" />&nbsp;
		<input class="button-disabled" type="submit" name="CustomActionButton[{$attribute.id}_edit_objects]" value="{'Edit selected'|i18n( 'design/standard/content/datatype' )}" disabled="disabled" />
	{/section}

	   {section show=array( 0, 2 )|contains( $class_content.type )}
		<input class="button" type="submit" name="CustomActionButton[{$attribute.id}_browse_objects]" value="{'Add existing objects'|i18n('design/standard/content/datatype')}" />
		<input type="hidden" name="{$attribute_base}_browse_for_object_browse_type[{$attribute.id}]" value="{$browse_object_browse_type|wash}" />
		{section show=$browse_object_start_node}
		    <input type="hidden" name="{$attribute_base}_browse_for_object_start_node[{$attribute.id}]" value="{$browse_object_start_node|wash}" />
		{/section}
	    {section-else}
		<input class="button-disabled" type="submit" name="CustomActionButton[{$attribute.id}_browse_objects]" value="{'Add existing objects'|i18n( 'design/standard/content/datatype' )}" disabled="disabled" />
	    {/section}
{/section}

{section show=and( lt($class_content.selection_type,2), $can_create, array( 0, 1 )|contains( $class_content.type ) )}

    <select class="combobox" name="{$attribute_base}_new_class[{$attribute.id}]">
    {section name=Class loop=$class_list}
        <option value="{$:item.id}">{$:item.name|wash}</option>
    {/section}
    </select>
    {section show=$new_object_initial_node_placement}
        <input type="hidden" name="{$attribute_base}_object_initial_node_placement[{$attribute.id}]" value="{$new_object_initial_node_placement|wash}" />
    {/section}
        <input class="button" type="submit" name="CustomActionButton[{$attribute.id}_new_class]" value="{'Create new object'|i18n( 'design/standard/content/datatype' )}" />

{/section}


</div>

{/default}