#!/bin/sh -e
APP=db
VERS=4.2.52
BDIR=`pwd`
PREFIX=$BDIR/inst
LD_LIBRARY_PATH=
LD_RUN_PATH=
CPPFLAGS="-I$PREFIX/include"
CC=gcc
CFLAGS="-g -O1"
LDFLAGS="-L$PREFIX/lib"
EDITOR="vi"
PATCH="/usr/bin/patch"
export LD_LIBRARY_PATH LD_RUN_PATH CC CFLAGS CPPFLAGS LDFLAGS EDITOR

# Create install dir if it doesn't exist
if [ ! -d $PREFIX ]; then
    mkdir -p $PREFIX/include $PREFIX/lib
fi

/bin/rm -rf $APP-$VERS
gzip -dc $APP-$VERS.tar.gz | tar xvf -
PATCHES=$(/bin/ls -1 $BDIR/db-patch.$VERS.* | sort)
if [ -n "$PATCHES" ]; then
    for p in $PATCHES; do
        cd $APP-$VERS
        echo "Applying Patch $p . . ."
        $PATCH -p0 < $p
        echo " . . . done"
        cd $BDIR
    done
fi
cd $APP-$VERS/build_unix
../dist/configure --prefix=$PREFIX \
    --disable-shared --enable-static
make all install
/bin/rm -rf $PREFIX/docs
cd $BDIR
