{* DO NOT EDIT THIS FILE! Use an override template instead. *}
 {pdf(text, "pdf/ezenhancedobjectrelation NEVER TESTED")|wash(pdf))}

{section show=$attribute.content}
  {pdf(link, hash(url, concat('content/view/full/',$attribute.content.main_node_id)|ezurl(no),
                  text, $attribute.content.name|wash(pdf)))};
{section-else}
   {pdf(text, "No relation"|i18n("design/standard/content/datatype")|wash(pdf))}
{/section}

{section name=Relation loop=$attribute.content.id_list sequence=array(bglight,bgdark)}
{*     <li>{content_view_gui view=pdf content_object=fetch(content,object,hash(object_id,$:item))}</li>
*}
{/section}
