{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*<ul class='related_object'>
{section name=Relation loop=$attribute.content.id_list sequence=array(bglight,bgdark)}
     <li>{content_view_gui view=text_linked content_object=fetch(content,object,hash(object_id,$:item))}</li>
{/section}
</ul>*}

<div class='related_object'>
{*section show=is_object($attribute.content)*}
{section show=is_array($attribute.content)}
{section name=Relation loop=$attribute.content.id_list sequence=array(bglight,bgdark)}
{let related=fetch(content,object,hash(object_id,$:item))}
     {node_view_gui view=line content_node=$:related.main_node}
{/let}
     {* the node_view is easier to override content_view_gui view=line content_object=fetch(content,object,hash(object_id,$:item))*}
{/section}
{/section}
</div>
