#!/bin/bash
EXTENSION_NAME="GeSHi"
EXTENSION_IDENTIFIER="geshi"
EXTENSION_SUMMARY="Syntax highlighting using GeSHi"
EXTENSION_LICENSE="GPL"
EXTENSION_VERSION="1.0beta1"
EXTENSION_PUBLISH_VERSION="3.5"
EXTENSION_ARCHIVE_NAME="geshi"
EXTENSION_PHP_VERSION="4.3.2"

