<fieldset> 
{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
{let class_content=$attribute.contentclass_attribute.content}

{switch match=$class_content.selection_type}

{case match=0} {* Browse *}
This choice shouldn't show up. Please select another selection method, and inform me (xavier) on the forum about this message.
    {section show=$attribute.content}
        <p class="box">{content_view_gui view=text_linked content_object=$attribute.content}</p>
    {section-else}
        <p class="box">{"No relation"|i18n("design/standard/content/datatype")}</p>
    {/section}

    <input type="hidden" name="{$attribute_base}_data_object_relation_id_{$attribute.id}" value="{$attribute.data_int}" />
    {section show=$attribute.content}
        <input class="button" type="submit" name="BrowseObjectButton_{$attribute.id}" value="{'Replace object'|i18n('design/standard/content/datatype')}" />
        <input class="button" type="submit" name="RemoveObjectButton_{$attribute.id}" value="{'Remove object'|i18n('design/standard/content/datatype')}" />
    {section-else}
        <input class="button" type="submit" name="BrowseObjectButton_{$attribute.id}" value="{'Find object'|i18n('design/standard/content/datatype')}" />
    {/section}
    <input type="hidden" name="CustomActionButton[{$attribute.id}_set_object_relation]" value="{$attribute.id}" />

{/case}

{case match=1} {* Dropdown list *}
    <div class="buttonblock">
    <select name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[{$node.node_id}]">
        {section show=$attribute.contentclass_attribute.is_required|not}
            <option value="" {section show=eq( $attribute.data_int, '' )}selected="selected"{/section}>{'No relation'|i18n( 'design/standard/content/datatype' )}</option>
        {/section}
        {let parent_node=fetch( content, node, hash( node_id, $class_content.default_selection_node ) )}
        {section var=node loop=fetch( content, list,
                                      hash( parent_node_id, $parent_node.node_id,
                                            sort_by, $parent_node.sort_array ) )}
            <option value="{$node.contentobject_id}" {$attribute.content.id_list|contains($node.contentobject_id)|choose( '', 'selected="selected"' )}>{$node.name|wash}</option>
        {/section}
        {/let}
    </select>

    </div>
{/case}

{case match=2} {* radio button *}
        {section show=$attribute.contentclass_attribute.is_required|not}
            <input type="radio" name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[single]" {section show=eq( $attribute.data_int, '' )}selected="selected"{/section}>{'No relation'|i18n( 'design/standard/content/datatype' )}</input><br />
        {/section}
        {let parent_node=fetch( content, node, hash( node_id, $class_content.default_selection_node ) )}
        {section var=node loop=fetch( content, list,
                                      hash( parent_node_id, $parent_node.node_id,
                                            sort_by, $parent_node.sort_array ) )}
           <input type="radio" name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[single]" value="{$node.contentobject_id}" {$attribute.content.id_list|contains($node.contentobject_id)|choose( '', 'checked="checked"' )}>{$node.name|wash}</input>  <br/>
        {/section}
        {/let}
{/case}


{case match=3} {* check box *}
{section show=$class_content.default_selection_node}
        {let parent_node=fetch( content, node, hash( node_id, $class_content.default_selection_node ) )}
        {section var=node loop=fetch( content, list,
                                      hash( parent_node_id, $parent_node.node_id,
                                            sort_by, $parent_node.sort_array ) )}
           <input type="checkbox" name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[{$node.node_id}]" value="{$node.contentobject_id}" {$attribute.content.id_list|contains($node.contentobject_id)|choose( '','checked="checked"' )}>{$node.name|wash}</input>  <br/>
        {/section}
        {/let}
{/section}

{section show=$class_content.filter_class}
{section var=node loop=fetch( 'content', 
        'tree', 
        hash( 'parent_node_id',     2,
              'class_filter_type',  'include',
              'main_node_only', true(),
              "sort_by", array("name", true()),
              'class_filter_array', array( $class_content.filter_class ) ) )}

           <input type="checkbox" name="{$attribute_base}_data_object_relation_id_list_{$attribute.id}[{$node.node_id}]" value="{$node.contentobject_id}" {section show=$attribute.content}{$attribute.content.id_list|contains($node.contentobject_id)|choose( '','checked="checked"' )}{/section}>{$node.name|wash}</input>  <br/>
        {/section}
{/section}

{/case}
{/switch} 
{*Display objects marked for editing *}
{section show=is_set($attribute.content.edit_id_list)}
{section loop=$attribute.content.edit_id_list}
{let object=fetch( content, object, hash( object_id, $:item) )}
{section name=Attribute loop=$object.contentobject_attributes}
<div class="block">
{section show=$:item.display_info.edit.grouped_input}
<fieldset>
<legend>{$:item.contentclass_attribute.name}</legend>
{attribute_edit_gui attribute_base=concat( $attribute_base, '_ezorl_edit_object_', $:item.contentobject_id ) html_class='half' attribute=$:item}
</fieldset>

{section-else}
<label>{$:item.contentclass_attribute.name}:</label>
{attribute_edit_gui attribute_base=concat( $attribute_base, '_ezorl_edit_object_', $:item.contentobject_id ) html_class='half' attribute=$:item}
{/section}

{/section}
{/let}
{/section}
{/section}
{*XAV: when displaying a class selection, display an extra one</fieldset>*}
{*End displaying objects marked for editing*}

{section show=ne(0,$class_content.default_placement_node)}
<input class="button" type="submit" value="Create New" name="CustomActionButton[{$attribute.id}_new_object]" />
{/section}
{/let}
{/default}
</fieldset>
