{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let browse_indentation=5
     page_limit=15
     browse_list_count=fetch(content,list_count,hash(parent_node_id,$node_id,depth,1))
     object_array=fetch(content,list,hash(parent_node_id,$node_id,depth,1,offset,$view_parameters.offset,limit,$page_limit,sort_by,$main_node.sort_array))
     bookmark_list=fetch('content','bookmarks',array())
     recent_list=fetch('content','recent',array())
     browse_type=cond(is_set($browse.browse_type),$browse.browse_type,0)
     create_type=cond(is_set($browse.create_type),$browse.create_type,1)
     class_constraint_list=cond(is_set($browse.class_constraint_list),$browse.class_constraint_list,array())
     select_name='SelectedObjectIDArray'
     select_type='checkbox'
     select_attribute='contentobject_id'}

{section show=eq($browse.return_type,'NodeID')}
    {set select_name='SelectedNodeIDArray'}
    {set select_attribute='node_id'}
{/section}
{section show=eq($browse.selection,'single')}
    {set select_type='radio'}
{/section}

<form action={concat($browse.from_page)|ezurl} method="post">

<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>

    <td width="80%" valign="top">

{switch match=$browse_type}
        {case}
		{section show=$browse.description_template}
		    {include name=Description uri=$browse.description_template browse=$browse main_node=$main_node}
		{section-else}
		    <div class="maincontentheader">
		    <h1>{"Browse"|i18n("design/standard/content/browse")} - {$main_node.name|wash}</h1>
		    </div>

		    <p>{'To select objects, choose the appropriate radiobutton or checkbox(es), and click the "Choose" button.'|i18n("design/standard/content/browse")}</p>
		    <p>{'To select an object that is a child of one of the displayed objects, click the object name and you will get a list of the children of the object.'|i18n("design/standard/content/browse")}</p>
		{/section}
	{/case}
	{case match=1}
		<div class="maincontentheader">
			<h1>{"Dynamic List"|i18n("design/standard/content/browse")} - {$main_node.name|wash}</h1>
		</div>
		<p>{'To select objects, enter (part of the) name of the object you wish to select. A list will appear from which you can select objects by checking the appropriate checkbox(es). The filter is case-sensitive. You may combine keywords with the "&" sign, e.g. "New&Folder" finds "New Folder".'|i18n("design/standard/content/browse")}</p>
	{/case}
{/switch}
	

        {switch match=$browse_type}
        {case}
		<table class="list" width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
		    <th width="1">
		    </th>
		    <th width="69%">
		    {"Name"|i18n("design/standard/content/browse")}
		    </th>
		    <th width="30%">
		    {"Class"|i18n("design/standard/content/browse")}
		    </th>
		    <th width="30%">
		    {"Section"|i18n("design/standard/content/browse")}
		    </th>
		</tr>
		<tr>
		    <td class="bglight">
		    {section show=and( or( $browse.permission|not,
					   cond( is_set( $browse.permission.contentclass_id ),
						 fetch( content, access,
							hash( access, $browse.permission.access,
							      contentobject, $main_node,
							      contentclass_id, $browse.permission.contentclass_id ) ),
						 fetch( content, access,
							hash( access, $browse.permission.access,
							      contentobject, $main_node ) ) ) ),
				       $browse.ignore_nodes_select|contains( $main_node.node_id )|not() )}
		      {section show=is_array($browse.class_array)}
			{section show=$browse.class_array|contains($main_node.object.content_class.identifier)}
			  <input type="{$select_type}" name="{$select_name}[]" value="{$main_node[$select_attribute]}" {section show=eq($browse.selection,'single')}checked="checked"{/section} />
			{section-else}
			    &nbsp;
			{/section}
		      {section-else}
			<input type="{$select_type}" name="{$select_name}[]" value="{$main_node[$select_attribute]}" {section show=eq($browse.selection,'single')}checked="checked"{/section} />
		      {/section}
		    {section-else}
			&nbsp;
		    {/section}
		    </td>

		    <td class="bglight">
			{node_view_gui view=line content_node=$main_node node_url=false()}
			{section show=$main_node.depth|gt(1)}
			    <a href={concat("/content/browse/",$main_node.parent_node_id,"/")|ezurl}>
				[{'Up one level'|i18n('design/standard/content/browse')}]
			    </a>
			{/section}
		    </td>

		    <td class="bglight">
		    {$main_node.object.content_class.name|wash}
		    </td>

		    <td class="bglight">
		    {$main_node.object.section_id}
		    </td>
		</tr>
		{section name=Object loop=$object_array sequence=array(bgdark,bglight)}
		<tr class="{$Object:sequence}">
		    <td>
		    {section show=and( or( $browse.permission|not,
					   cond( is_set( $browse.permission.contentclass_id ),
						 fetch( content, access,
							hash( access, $browse.permission.access,
							      contentobject, $:item,
							      contentclass_id, $browse.permission.contentclass_id ) ),
						 fetch( content, access,
							hash( access, $browse.permission.access,
							      contentobject, $:item ) ) ) ),
				       $browse.ignore_nodes_select|contains($:item.node_id)|not() )}
		      {section show=is_array($browse.class_array)}
			{section show=$browse.class_array|contains($:item.object.content_class.identifier)}
			  <input type="{$select_type}" name="{$select_name}[]" value="{$:item[$select_attribute]}" />
			{section-else}
			  &nbsp;
			{/section}
		      {section-else}
			<input type="{$select_type}" name="{$select_name}[]" value="{$:item[$select_attribute]}" />
		      {/section}
		    {/section}
		    </td>

		    <td>
			<img src={"1x1.gif"|ezimage} width="{mul(sub($:item.depth,$main_node.depth),$browse_indentation)}" height="1" alt="" border="0" />

			 {node_view_gui view=line content_node=$Object:item node_url=cond( $browse.ignore_nodes_click|contains($Object:item.node_id)|not(), concat( 'content/browse/', $Object:item.node_id, '/' ), false() )}
		    </td>

		    <td>
			    {$Object:item.object.content_class.name|wash}
		    </td>

		    <td>
			    {$:item.object.section_id}
		    </td>
		</tr>
		{/section}
		</table>
        {/case}
        
        {case match=1}
		<script language="VBScript">
		Dim FilterString, cFilterExpr

		Sub Window_Onload()
			tbldisplay.innerHTML=""
			document.forms(2).cboCategory.value = "{"Enter name"|i18n("design/standard/content/view")}"
			document.forms(2).cboCategory.focus
			document.forms(2).cboCategory.select
		End Sub

		Sub cboCategory_OnKeyUp()
		    Call FilterGroupAndPeriod
		End Sub

		function check(id)		
			cFilterExpr = ""
			cFilterExpr = "ID ="&id
			document.forms(2).elements.object.filter = cFilterExpr
			document.forms(2).elements.Reset

			If document.forms(2).elements.recordset(3) = 1 Then
				document.forms(2).elements.recordset.update "Checked",0
			Else
				document.forms(2).elements.recordset.update "Checked",1
			End If

			Call FilterGroupAndPeriod
		End function

		Function Shorten(sString, sLength) 
			If Len (sString) > sLength Then 
				 Shorten = Left(sString,sLength) & "...." 
			Else 
				 Shorten = sString
			End If 
		End Function 

		function FilterGroupAndPeriod()
			newtbl="<table class=""list""><tr><th width=""5%""><div id=""name"">{"Name"|i18n("design/standard/content/view")}</div></th><th width=""95%""><div id=""description"">{"ID"|i18n("design/standard/content/view")}</div></th></tr><tr>"
			siteurl={"/content/view/full/"|ezurl}
			cFilterExpr = ""
			
			if Left(document.forms(2).cboCategory.value, 1)="^"  Then
				cFilterExpr = "Checked=1 | Name ="& Mid(document.forms(2).cboCategory.value,2,Len(document.forms(2).cboCategory.value)) & "*"
			Else
				cFilterExpr = "Checked=1 | Name =*"&document.forms(2).cboCategory.value & "*"
			End if

			if InStr(document.forms(2).cboCategory.value,"&") Then
				searchstring_array=Split(document.forms(2).cboCategory.value,"&") 		
				cFilterExpr ="Checked=1 | (Name=*" & join(searchstring_array,"* & Name=*") & "*)"
			End if

			document.forms(2).elements.object.filter = cFilterExpr
			document.forms(2).elements.Sort = "+Name"
			document.forms(2).elements.Reset

			If document.forms(2).elements.recordset.recordcount<250 and document.forms(2).elements.recordset.recordcount>0 Then

			Do
				link=Shorten(Replace(document.forms(2).elements.recordset(1), document.forms(2).cboCategory.value, "<strong>"&document.forms(2).cboCategory.value&"</strong>"),150)
				If document.forms(2).elements.recordset(3) = 1 Then
					checked="checked"
				Else
					checked=""
				End If

				newtbl=newtbl&"<tr><td><input type=""checkbox"" name=""SelectedObjectIDArray[]"" onClick='check("&document.forms(2).elements.recordset(0)&")' value="&document.forms(2).elements.recordset(0)&" "& checked &"></td><td>"&link&" (<a target=""_vblank"" href="&siteurl&"/"&document.forms(2).elements.recordset(2)& ">info</a>)</td></tr>"

				document.forms(2).elements.recordset.MoveNext
					
				Loop Until document.forms(2).elements.recordset.EOF
				document.forms(2).elements.recordset.moveFirst

				newtbl=newtbl&"</table>"
				tbldisplay.innerHTML=newtbl
			Else
				tbldisplay.innerHTML="<div class=""error"">{"Too many records found"|i18n("design/standard/content/view")}</div>"

				If document.forms(2).elements.recordset.recordcount=0 or document.forms(2).cboCategory.value="" Then				
					tbldisplay.innerHTML="<div class=""error"">{"No records found"|i18n("design/standard/content/view")}</div>"
				End If


			End If
		end function
		</script>


		<br/>		
		<p>{"Name"|i18n("design/standard/content/view")}:&nbsp;<input type="text" name="cboCategory" Class="Filters" style="width: 150px" value="{"Loading list, please wait..."|i18n("design/standard/content/view")}"></p>
		<br/><br/>	

		<object id="elements" CLASSID="clsid:333C7BC4-460F-11D0-BC04-0080C7055A83" width=1 height=1>
		    <param NAME="DataURL" VALUE={concat("/layout/set/datalist/content/view/full/",$browse.start_node)|ezurl}>
		    <param NAME="UseHeader" VALUE="True">
		    <param NAME="FieldDelim" VALUE="|">
		    <param NAME="RowDelim" VALUE="~">
		    <param NAME="Filter" Value="ID=0">
		</object>

		<TABLE id=tbldata name=tbldata datasrc=#elements  style="display:none">
			<TR><TD><DIV datafld="Name"></DIV></TD><TD><DIV datafld="ID"></DIV></TD></TR>
		</TABLE>			

		<span id=tbldisplay name=tbldisplay></span>
		</p>
		<hr>
        {/case}
        {/switch}
    </td>

    <td width="20">
    </td>
    
    {switch match=$browse_type}	
    {case} 
	    <td width="200" valign="top">

		{* Recent and bookmark start *}
		<table class="list" width="100%" border="0" cellspacing="0" cellpadding="0">

		<tr>
		    <th colspan="2">
			{"Top levels"|i18n("design/standard/content/browse")}
		    </th>
		</tr>

		<tr>
		    <td colspan="2">
			{'Switch top levels by clicking one of these items.'|i18n('design/standard/content/browse')}
		    </td>
		</tr>

		{section name=TopLevel loop=$browse.top_level_nodes
			 sequence=array(bgdark,bglight)}
		<tr class="{$:sequence}">
		    {let top_node=fetch( content, node, hash( node_id, $:item ) )}
		    <td width="1">
		    {section show=and( or( $browse.permission|not,
					   cond( is_set( $browse.permission.contentclass_id ),
						 fetch( content, access,
							hash( access, $browse.permission.access,
							      contentobject, $:top_node,
							      contentclass_id, $browse.permission.contentclass_id ) ),
						 fetch( content, access,
							hash( access, $browse.permission.access,
							      contentobject, $:top_node ) ) ) ),
				       $browse.ignore_nodes_select|contains( $:item )|not() )}
		      {section show=is_array($browse.class_array)|not()}
			<input type="{$select_type}" name="{$select_name}[]" value="{$:item}" />
		      {section-else}
			&nbsp;
		      {/section}
		    {section-else}
		      &nbsp;
		    {/section}
		    </td>

		    <td>
			{node_view_gui view=line content_node=$:top_node
				       node_url=cond( eq( $:item, $main_node.node_id ), false(),
						      $browse.ignore_nodes_click|contains( $:top_node.node_id )|not(), concat( 'content/browse/', $:top_node.node_id, '/' ), false() )}
		    </td>
		    {/let}
		</tr>
		{/section}

		<tr>
		    <th colspan="2">
			{"Bookmarks"|i18n("design/standard/content/browse")}
		    </th>
		</tr>

		{section name=Bookmark loop=$bookmark_list show=$bookmark_list sequence=array(bgdark,bglight)}
		<tr class="{$:sequence}">
		    <td width="1">
		    {section show=and( or( $browse.permission|not,
					   cond( is_set( $browse.permission.contentclass_id ),
						 fetch( content, access,
							hash( access, $browse.permission.access,
							      contentobject, $:item.node,
							      contentclass_id, $browse.permission.contentclass_id ) ),
						 fetch( content, access,
							hash( access, $browse.permission.access,
							      contentobject, $:item.node ) ) ) ),
				       $browse.ignore_nodes_select|contains( $:item.node_id )|not() )}
		      {section show=is_array($browse.class_array)}
			{section show=$browse.class_array|contains($:item.object.content_class.identifier)}
			  <input type="{$select_type}" name="{$select_name}[]" value="{$:item.node[$select_attribute]}" />
			{section-else}
			  &nbsp;
			{/section}
		      {section-else}
			<input type="{$select_type}" name="{$select_name}[]" value="{$:item.node[$select_attribute]}" />
		      {/section}
		    {section-else}
		      &nbsp;
		    {/section}
		    </td>

		    <td>
			{node_view_gui view=line content_node=$:item.node
				       node_url=cond( eq( $:item.node_id, $main_node.node_id ), false(),
						      $browse.ignore_nodes_click|contains( $:item.node_id )|not(), concat( 'content/browse/', $:item.node_id, '/' ), false() )}
		    </td>
		</tr>
		{section-else}
		<tr>
		    <td colspan="2">
			{'Bookmark items are managed using %bookmarkname in the %personalname part.'
			 |i18n('design/standard/content/browse',,
			       hash('%bookmarkname',concat('<i>','My bookmarks'|i18n('design/standard/content/browse'),'</i>'),
				    '%personalname',concat('<i>','Personal'|i18n('design/standard/content/browse'),'</i>')))}
		    </td>
		</tr>
		{/section}

		<tr height="6">
		    <td>
		    </td>
		</tr>

		<tr>
		    <th colspan="2">
			{"Recent items"|i18n("design/standard/content/browse")}
		    </th>
		</tr>

		{section show=$recent_list}
		    {section name=Recent loop=$recent_list sequence=array(bgdark,bglight)}
		    <tr class="{$:sequence}">
			<td width="1">
			{section show=and( or( $browse.permission|not,
					       cond( is_set( $browse.permission.contentclass_id ),
						     fetch( content, access,
							    hash( access, $browse.permission.access,
								  contentobject, $:item.node,
								  contentclass_id, $browse.permission.contentclass_id ) ),
						     fetch( content, access,
							    hash( access, $browse.permission.access,
								  contentobject, $:item.node ) ) ) ),
					   $browse.ignore_nodes_select|contains( $:item.node_id )|not() )}
			  {section show=is_array($browse.class_array)|not()}
			    <input type="{$select_type}" name="{$select_name}[]" value="{$:item[$select_attribute]}" />
			  {section-else}
			    &nbsp;
			  {/section}
			{section-else}
			  &nbsp;
			{/section}
			</td>

			<td>
			{node_view_gui view=line content_node=$:item.node
				       node_url=cond( eq( $:item.node_id, $main_node.node_id ), false(),
						      $browse.ignore_nodes_click|contains( $:item.node_id )|not(), concat( 'content/browse/', $:item.node_id, '/' ), false() )}
			</td>
		    </tr>
		    {/section}
		{section-else}
		<tr>
		    <td colspan="2">
			{'Recent items are added on publishing.'|i18n('design/standard/content/browse')}
		    </td>
		</tr>
		{/section}

		</table>
		{* Recent and bookmark end *}

	    </td>
    {/case}
    {case match=1}
    {/case}
    {/switch}

</tr>
</table>
{switch match=$browse_type}	
	{case} 
		{include name=Navigator
		 uri='design:navigator/google.tpl'
		 page_uri=concat('/content/browse/',$main_node.node_id)
		 item_count=$browse_list_count
		 view_parameters=$view_parameters
		 item_limit=$page_limit}
	{/case}	
	{case match=1}
	{/case}
{/switch}

		{section name=Persistent show=$browse.persistent_data loop=$browse.persistent_data}
		    <input type="hidden" name="{$:key|wash}" value="{$:item|wash}" />
		{/section}

		<input type="hidden" name="BrowseActionName" value="{$browse.action_name}" />
		
		{section show=$browse.browse_custom_action}
		<input type="hidden" name="{$browse.browse_custom_action.name}" value="{$browse.browse_custom_action.value}" />
		{/section}
		
		<input class="button" type="submit" name="SelectButton" value="{'Select'|i18n('design/standard/content/browse')}" />
		
		{section show=$cancel_action}
		<input type="hidden" name="BrowseCancelURI" value="{$cancel_action}" />
		{/section}
		
		 <input class="button" type="submit" name="BrowseCancelButton" value="{'Cancel'|i18n( 'design/standard/content/browse' )}" />
		</form>
		<br/>
		{switch match=$browse_type}	
			{case} 
				{section show=$create_type|lt(2)}
				
					<form name="test" method="post" action={"content/action"|ezurl}>
					<table>
						<tr>
						    <th colspan="2" align="left">
							{"Create new"|i18n("design/standard/content/browse")}
						    </th>
						</tr>
						<tr class="bgdark">
						<td colspan="2" align="left">
						<select	name="ClassID" class="classcreate">
							{section show=$class_constraint_list|count|lt(1)}
								{section name=Classes loop=$main_node.object.can_create_class_list}
									<option value="{$Classes:item.id}">{$Classes:item.name}</option>
								{/section}
							{section-else}
								{section name=Classes loop=fetch( class, list )}
									{section show=$class_constraint_list|contains($Classes:item.identifier)}
										<option value="{$Classes:item.id}">{$Classes:item.name}</option>
									{/section}
								 {/section}

							{/section}
						</select>
						<input class="menubutton" type="submit" name="NewButton" value="{'New'|i18n('design/standard/content/browse')}" />
						<input class="menubutton" type="hidden" name="RedirectURIAfterPublish" value="/content/browse/" />
						<input class="menubutton" type="hidden" name="NodeID" value="{$main_node.node_id}" />
						</td>
						</tr>
					</table>
					</form>
				{/section}
			{/case}	
			{case match=1}
			{section show=$create_type|lt(2)}
				<form name="test" method="post" action={"content/action"|ezurl}>
				<table>
					<tr>
					    <th colspan="2" align="left">
						{"Create new"|i18n("design/standard/content/browse")}
					    </th>
					</tr>
					<tr class="bgdark">
					<td colspan="2" align="left">
					<select	name="ClassID" class="classcreate">	
					    {section name=Classes loop=fetch( class, list )}
						{section show=$class_constraint_list|contains($Classes:item.identifier)}
							<option value="{$Classes:item.id}">{$Classes:item.name}</option>
						{/section}
					    {/section}
					</select>
					<input class="button" type="submit" name="NewButton" value="{'New'|i18n('design/standard/content/browse')}" />
					<input class="menubutton" type="hidden" name="RedirectURIAfterPublish" value="/content/browse/{$main_node.node_id}" />
					<input class="menubutton" type="hidden" name="NodeID" value="{$browse.default_placement.node_id}" />
					</td>
					</tr>
				</table>
				</form>
			{/section}
			{/case}
		{/switch}
	

{/let}
